name: "Captain CI example"
on:
  pull_request:
  push:
    paths-ignore:
      - README.md
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: rwx-research/setup-captain@v1
      - run: |
          # unset GITHUB env to imitate non-github CI
          for var in $(env | grep '^GITHUB' | sed 's/^\(GITHUB[^=]*\)=.*$/\1/'); do unset $var; done
          scripts/run-tests.sh
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}
          CAPTAIN_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  test-partitioned:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        partition_index: [0, 1]
        partition_total: [2]
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: rwx-research/setup-captain@v1
      - run: |
          # unset GITHUB env to imitate non-github CI
          for var in $(env | grep '^GITHUB' | sed 's/^\(GITHUB[^=]*\)=.*$/\1/'); do unset $var; done
          scripts/run-tests-partitioned.sh
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}
          CAPTAIN_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          CAPTAIN_PARTITION_INDEX: ${{ matrix.partition_index }}
          CAPTAIN_PARTITION_TOTAL: ${{ matrix.partition_total }}
